import React, {useState, useEffect} from 'react'
import { Loader, Card, FormField  } from '../components'

const RenderCards = ({data, title})=>{
  if(data?.length > 0){
    return data.map((post)=> <Card key={post._id} {...post}/>)
  }
  return (
    <h2 className="mt-5 font-bold text-xl uppercase text-[#6449ff] ">{title}</h2>
  )
}


const Home = () => {

  const [loading, setLoading] = useState(false)
  const [allpost, setAllPost] = useState(null)
  const [searchKeyword, setSearchedKeyword] = useState('')

  useEffect(() => {
    const fetchPost = async()=>{
      setLoading(true)
      try {
        const response = await fetch("http://localhost:5000/api/v1/get-allpost",{
          method: "GET",
          headers:{'Content-Type': 'application/json',},
          body: JSON.stringify(form)

        })
        if(response.status===201){
          const result = await response.json()
          setAllPost(result.data.reverse())
        }
      } catch (error) {
        alert(error)
      }
      finally{
        setLoading(false)
      }
    }
    fetchPost()
  }, [])
  

  return (
    <section className='max-w-7xl mx-auto text-start' >
      <div>
        <h1 className='font-extrabold text-[#2223328] text-5xl'>The community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-base max-w-[500px]'>Browse a collection of imaginative and visually stunning images generated by DALL-E-Ai </p>
      </div>
      <div className="mt-16">
        <FormField/>
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader/>
          </div>
        ):
        (
          <>
          {searchKeyword && (
            <h2 className='font-medium text-[#666e75] text-xl mb-3'>
              Showing results for <span className='text-[#222328]'>{searchKeyword}</span>
            </h2>
          )}
          <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-col-2 grid-cols-1 gap-3">

            {searchKeyword? (
              <RenderCards
              data = {[]}
              title = "No search result found"
              />
            ):
            (
              <RenderCards
              data = {[]}
              title = "No posts found"
              />
            )
          
          }

          </div>
          </>
        )
        }
      </div>
    </section>
  )
}

export default Home
