import React, {useState} from 'react'
import { useNavigate } from 'react-router-dom'
import {getRandomPrompt} from '../utils'
import { preview } from '../assets'
import { Loader, Card, FormField  } from '../components'

const CreatePost = () => {
  const navigate  = useNavigate()
  const [form, setForm] = [{
    fname: '',
    prompt: '',
    pic: '',
  }]
  const [generatingImg, setGeneratingImg] = useState(null)
  const [loading, setLoading] = useState(null)
  const handleSubmitForm = ()=>{

  }

  const handleChange = (e)=>{

  }
  const handleSurpriseMe = ()=>{

  }
  

  return (
    <>
      <section className='max-w-7xl mx-auto text-start' >
      <div>
        <h1 className='font-extrabold text-[#2223328] text-5xl'>Create</h1>
        <p className='mt-2 text-[#666e75] text-base max-w-[500px]'>Create collection of imaginative and visually stunning images generated by DALL-E-Ai and share them with the community</p>
      </div>

      <form className="mt-16 max-w-3xl" onSubmit={handleSubmitForm}>
        <div className="flex flex-col gap-5 ">
          <FormField
          labelName = "Your name"
          type = "text"
          name = "fname"
          placeholder = "Muhammad Umer"
          value = {form.fname}
          handleChange = {handleChange}
          />

<FormField
          labelName = "Prompt"
          type = "text"
          name = "prompt"
          placeholder = "Muhammad Umer"
          value = {form.prompt}
          handleChange = {handleChange}
          isSurpriseMe
          handleSurpriseMe={handleSurpriseMe}
          />

        </div>

      </form>


      </section>
    </>
  )
}

export default CreatePost
