import React, {useState, useEffect} from 'react'
import { Loader, Card, FormField  } from '../components'
const Home = () => {

  const [loading, setLoading] = useState(false)
  const [allpost, setAllPost] = useState(null)

  return (
    <section className='max-w-7xl mx-auto text-start' >
      <div>
        <h1 className='font-extrabold text-[#2223328] text-5xl'>The community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-base max-w-[500px]'>Browse a collection of imaginative and visually stunning images generated by DALL-E-AI </p>
      </div>
    </section>
  )
}

export default Home
